---
aap_configuration_async_retries: 60
aap_configuration_async_delay: 5
hub_collection_remotes:
  - name: community
    url: https://galaxy.ansible.com/api/
    requirements:
      - community.docker
      - community.general
      - community.crypto
      - cloud.terraform

hub_collection_repositories:
  - name: community
    remote: community
...
