---
version: 3

dependencies:
  galaxy: requirements.yml
  system: system.txt
  python: requirements.txt

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest 

options:
  package_manager_path: "/usr/bin/microdnf"

additional_build_steps:
  prepend_base:
    - RUN $PKGMGR install -y gcc make python3.11-devel pkg-config systemd-devel && $PKGMGR clean all
  append_final:
    - RUN pip3 check
    # Clean up
    - >
      RUN $PKGMGR update -y &&
      $PKGMGR clean all &&
      rm -rf /var/cache/{dnf,yum} &&
      rm -rf /var/lib/dnf/history.* &&
      rm -rf /var/log/*
