---
version: 3

dependencies:
  galaxy: requirements.yml

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

options:
  package_manager_path: "/usr/bin/microdnf"

additional_build_steps:
  prepend_base:
    - RUN whoami
    - RUN cat /etc/os-release
    - RUN echo PKGMGR = $PKGMGR, PYCMD = $PYCMD
    - RUN $PYCMD -m pip install --upgrade pip
  append_final:
    # Verify installed packages have compatible dependencies
    # Logged issue https://github.com/ansible/ansible-builder/issues/416
    - RUN pip3 check
    # Clean up
    - >
      RUN $PKGMGR update -y &&
      $PKGMGR clean all &&
      rm -rf /var/cache/{dnf,yum} &&
      rm -rf /var/lib/dnf/history.* &&
      rm -rf /var/log/*
