---
controller_groups_dev:
- name: PSQL_Servers
  description: Group for Postgres SQL Servers
  inventory: test_inventory
  variables:
    myvars: example1
  hosts:
   - PSQL111
   - PSQL222
   - PSQL333
  children:
   - group111
   - group222
   - group333